# Generated by Django 2.2.5 on 2021-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_author',
            field=models.CharField(max_length=20, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_content',
            field=models.CharField(max_length=1000, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_title',
            field=models.CharField(max_length=30, verbose_name='글 제목'),
        ),
    ]
