# Generated by Django 2.2.5 on 2021-08-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20210805_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
